import { useParams, useNavigate, useLocation } from 'react-router-dom';
import { useState, useEffect } from 'react';
import { ArrowLeft } from 'lucide-react';
import NodeDetailHeader from '../../components/mentor/NodeDetailHeader';
import ChecklistSection from '../../components/mentor/ChecklistSection';
import MaterialsSection from '../../components/mentor/MaterialsSection';
import TipsSection from '../../components/mentor/TipsSection';
import QuizSection from '../../components/mentor/QuizSection';
import { getTips } from '../../services/roadmapService';
import { getQuizzesByNode } from '../../services/quizService';
import { getNodeDetails, syncNodeDetails } from '../../services/nodeService';

const NodeDetailsPage = () => {
  const { roadmapId, nodeId } = useParams();
  const navigate = useNavigate();
  const location = useLocation();

  // State for tips
  const [tips, setTips] = useState([]);

  // State for quizzes
  const [quizzes, setQuizzes] = useState([]);

  // State for checklists & materials
  const [checklists, setChecklists] = useState([]);
  const [materials, setMaterials] = useState([]);
  const [nodeDetailsLoading, setNodeDetailsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  // Get node data from state if available, otherwise we will use the fetched data
  const [nodeData, setNodeData] = useState(location.state?.nodeData || {
    id: parseInt(nodeId),
    title: 'Đang tải...',
    description: '',
    category: '',
    nodeNumber: 0,
    totalNodes: 0,
  });

  // Fetch node details
  useEffect(() => {
    if (roadmapId === 'new') {
      alert('Vui lòng lưu Lộ trình trước khi thêm chi tiết (tài liệu, checklist, bài trắc nghiệm) cho Node.');
      navigate('/mentor/create-roadmap');
      return;
    }

    const fetchNodeData = async () => {
      setNodeDetailsLoading(true);
      try {
        const data = await getNodeDetails(nodeId);
        if (data) {
          setChecklists(data.checklists || []);
          setMaterials(data.materials || []);
          setNodeData(prev => ({
            ...prev,
            title: data.title,
            description: data.description,
            // Keep category and numbers if they were passed via router state, else fallback
          }));
        }
      } catch (err) {
        console.error('Failed to fetch node details:', err);
      } finally {
        setNodeDetailsLoading(false);
      }
    };
    fetchNodeData();
  }, [nodeId, roadmapId, navigate]);

  // Fetch tips on component mount
  useEffect(() => {
    const fetchTips = async () => {
      try {
        const data = await getTips(nodeId);
        setTips(data || []);
      } catch (err) {
        console.error('Failed to fetch tips:', err);
        // Fallback to empty array on error
        setTips([]);
      }
    };

    fetchTips();
  }, [nodeId]);

  // Fetch quizzes on component mount
  useEffect(() => {
    const fetchQuizzes = async () => {
      try {
        const data = await getQuizzesByNode(nodeId);
        setQuizzes(data || []);
      } catch (err) {
        console.error('Failed to fetch quizzes:', err);
        setQuizzes([]);
      }
    };

    fetchQuizzes();
  }, [nodeId]);

  // Removed mock data for checklists and materials

  const handleBack = () => {
    // Navigate back to create roadmap page when editing nodes during creation
    if (roadmapId === 'new') {
      navigate('/mentor/create-roadmap');
    } else {
      navigate(`/mentor/roadmaps/${roadmapId}/edit`);
    }
  };

  const handleRefreshTips = () => {
    const fetchTips = async () => {
      try {
        const data = await getTips(nodeId);
        setTips(data || []);
      } catch (err) {
        console.error('Failed to refresh tips:', err);
      }
    };

    fetchTips();
  };

  const handleRefreshQuizzes = () => {
    const fetchQuizzes = async () => {
      try {
        const data = await getQuizzesByNode(nodeId);
        setQuizzes(data || []);
      } catch (err) {
        console.error('Failed to refresh quizzes:', err);
      }
    };

    fetchQuizzes();
  };

  const handleSaveChanges = async () => {
    setIsSaving(true);
    try {
      const updatedData = await syncNodeDetails(nodeId, {
        checklists,
        materials,
      });
      // Optionally update local state with returned data if IDs were generated by backend
      if (updatedData) {
        setChecklists(updatedData.checklists || []);
        setMaterials(updatedData.materials || []);
      }
      alert('Lưu thay đổi thành công!');
    } catch (error) {
      console.error('Failed to save changes:', error);
      alert('Có lỗi xảy ra khi lưu thay đổi!');
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 py-8">
      <div className="max-w-7xl mx-auto px-4">
        {/* Action Buttons */}
        <div className="flex items-center gap-3 mb-8">
          <button
            onClick={handleBack}
            className="flex items-center gap-2 text-indigo-600 hover:text-indigo-700 font-medium transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Quay lại
          </button>
        </div>

        {/* Header */}
        <NodeDetailHeader node={nodeData} />

        {/* Main Content - 2 Column Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Left Column - Sections (70%) */}
          <div className="lg:col-span-2 space-y-6">
            <ChecklistSection items={checklists} onChange={setChecklists} />
            <MaterialsSection materials={materials} onChange={setMaterials} />
            <TipsSection tips={tips} nodeId={nodeData.id} onRefresh={handleRefreshTips} />
            <QuizSection quizzes={quizzes} onRefresh={handleRefreshQuizzes} />
          </div>

          {/* Right Column - Summary (30%) */}
          <div className="lg:col-span-1">
            <div className="bg-white rounded-2xl p-6 shadow-sm border border-slate-100 sticky top-8">
              <h2 className="text-lg font-semibold text-slate-900 mb-4">Tóm Tắt Node</h2>
              
              <div className="space-y-4">
                {/* Node Info */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-slate-600">Node:</span>
                    <span className="font-semibold text-slate-900">{nodeData.nodeNumber} of {nodeData.totalNodes}</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-slate-600">Danh Mục:</span>
                    <span className="font-semibold text-slate-900">{nodeData.category}</span>
                  </div>
                </div>

                <div className="h-px bg-slate-200"></div>

                {/* Material Count */}
                <div className="flex items-center justify-between">
                  <span className="text-sm text-slate-600">Materials:</span>
                  <span className="font-semibold text-slate-900">{materials.length}</span>
                </div>

                {/* Tips Count */}
                <div className="flex items-center justify-between">
                  <span className="text-sm text-slate-600">Tips:</span>
                  <span className="font-semibold text-slate-900">{tips.length}</span>
                </div>

                {/* Quiz Count */}
                <div className="flex items-center justify-between">
                  <span className="text-sm text-slate-600">Quizzes:</span>
                  <span className="font-semibold text-slate-900">{quizzes.length}</span>
                </div>

                <div className="h-px bg-slate-200"></div>

                {/* Action Button */}
                <button
                  onClick={handleSaveChanges}
                  disabled={isSaving || nodeDetailsLoading}
                  className={`w-full font-medium py-2.5 rounded-lg transition-colors text-white ${
                    isSaving || nodeDetailsLoading
                      ? 'bg-indigo-400 cursor-not-allowed'
                      : 'bg-indigo-600 hover:bg-indigo-700'
                  }`}
                >
                  {isSaving ? 'Đang lưu...' : 'Lưu Thay Đổi'}
                </button>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
};

export default NodeDetailsPage;
